# Generated by Django 3.2.7 on 2021-09-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='alias',
        ),
        migrations.AddField(
            model_name='hero',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
